#!/bin/bash
# Run integration tests against a running server
# Usage: ./scripts/test-integration.sh [local|compose]
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

cd "$ROOT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parse arguments
MODE="${1:-local}"

cleanup() {
  echo -e "${YELLOW}Cleaning up...${NC}"
  ./scripts/stop-all.sh 2>/dev/null || true
}

wait_for_server() {
  local url="$1"
  local max_attempts=30
  local attempt=1

  echo -e "${YELLOW}Waiting for server at $url...${NC}"
  while [ $attempt -le $max_attempts ]; do
    if curl -s "$url/health" > /dev/null 2>&1; then
      echo -e "${GREEN}Server is ready!${NC}"
      return 0
    fi
    echo "Attempt $attempt/$max_attempts..."
    sleep 2
    attempt=$((attempt + 1))
  done

  echo -e "${RED}Server failed to start within timeout${NC}"
  return 1
}

case "$MODE" in
  local|l)
    echo -e "${GREEN}Running integration tests in LOCAL mode${NC}"

    # Stop any running services to avoid port conflicts
    cleanup

    # Build if needed
    if [ ! -d "node/packages/maxq/dist" ]; then
      echo "Building project..."
      ./scripts/build.sh --no-format
    fi

    # Run tests (self-contained: spins up its own server and temp DB)
    echo -e "${GREEN}Running MaxQ tests...${NC}"
    cd node/packages/maxq-integration-tests
    npm test
    cd "$ROOT_DIR"

    echo -e "${GREEN}All tests passed!${NC}"
    ;;

  compose|c)
    echo -e "${GREEN}Running integration tests against DOCKER COMPOSE${NC}"

    # Stop any running services
    cleanup

    # Create host data directory for docker compose
    TEST_DIR="$ROOT_DIR/.tests/compose-test-$(date +%s)"
    HOST_DATA_DIR="$TEST_DIR/data"
    HOST_FLOWS_DIR="$ROOT_DIR/node/packages/maxq-integration-tests/test-flows"
    mkdir -p "$HOST_DATA_DIR/maxq/db"

    # Create temporary env file for docker-compose (test configuration)
    TEST_ENV_FILE="$TEST_DIR/.env.test"
    cat > "$TEST_ENV_FILE" << EOF
# Test environment - auto-generated by test-integration.sh
NODE_ENV=test

# Server
MAXQ_SERVER_HOST=0.0.0.0
MAXQ_SERVER_PORT=5003

# Database (container path)
MAXQ_DATA_DIR=/app/data/maxq/db

# Flows (container path)
MAXQ_FLOWS_ROOT=/app/flows

# Logging
LOG_LEVEL=info
EOF

    # Export for docker-compose (volume mounts and env file)
    export MAXQ_DATA_HOST_DIR="$HOST_DATA_DIR/maxq/db"
    export MAXQ_FLOWS_HOST_DIR="$HOST_FLOWS_DIR"
    export ENV_FILE="$TEST_ENV_FILE"

    TEST_EXIT_CODE=0

    # Docker compose command
    COMPOSE_CMD="docker compose -f devenv/docker-compose.yml"

    # Run migrations
    echo "Running MaxQ migrations..."
    $COMPOSE_CMD run --rm maxq-migrations

    # Start server
    echo "Starting MaxQ server..."
    $COMPOSE_CMD up -d maxq

    if ! wait_for_server "http://localhost:5003"; then
      echo -e "${RED}MaxQ server failed to start. Showing logs:${NC}"
      $COMPOSE_CMD logs maxq-migrations
      $COMPOSE_CMD logs maxq
      $COMPOSE_CMD down
      rm -rf "$TEST_DIR"
      exit 1
    fi

    # Run tests from host against Docker container
    echo -e "${GREEN}Running MaxQ tests against Docker...${NC}"
    export TEST_URL="http://localhost:5003"
    export TEST_DB_PATH="$HOST_DATA_DIR/maxq/db/maxq.db"
    cd node/packages/maxq-integration-tests
    npm test || TEST_EXIT_CODE=$?
    cd "$ROOT_DIR"

    # Cleanup
    $COMPOSE_CMD down
    rm -rf "$TEST_DIR"

    if [ $TEST_EXIT_CODE -eq 0 ]; then
      echo -e "${GREEN}All Docker Compose tests passed!${NC}"
    else
      echo -e "${RED}Docker Compose tests failed!${NC}"
    fi

    exit ${TEST_EXIT_CODE:-0}
    ;;

  *)
    echo "Usage: $0 [local|compose]"
    echo "  local   - Run tests against local Node.js server"
    echo "  compose - Run tests against Docker Compose setup"
    exit 1
    ;;
esac
